language: cpp
git:
  depth: false
matrix:
  include:
  - os: linux
    dist: xenial
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - sourceline: ppa:beineri/opt-qt-5.14.2-xenial
        - sourceline: ppa:jonathonf/gcc-9.0
        packages:
        - gcc-9
        - g++-9
        - qt514-meta-minimal
        - qt514quickcontrols
        - qt514quickcontrols2
        - qt514graphicaleffects
        - qt514webengine
        - qt514svg
        - libgl-dev
        - ninja-build
    before_script:
    - curl -vL https://github.com/probonopd/linuxdeployqt/releases/download/6/linuxdeployqt-6-x86_64.AppImage
      -o linuxdeployqt
    - chmod +x linuxdeployqt
    script:
    - misc/travis/linux.sh
  - os: linux
    dist: xenial
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - sourceline: ppa:beineri/opt-qt-5.14.2-xenial
        - sourceline: deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-10 main
          key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
        packages:
        - clang-10
        - libc++-10-dev
        - libc++abi-10-dev
        - qt514-meta-minimal
        - qt514quickcontrols
        - qt514quickcontrols2
        - qt514graphicaleffects
        - qt514webengine
        - qt514svg
        - libgl-dev
        - ninja-build
    before_script:
    - curl -vL https://github.com/probonopd/linuxdeployqt/releases/download/6/linuxdeployqt-6-x86_64.AppImage
      -o linuxdeployqt
    - chmod +x linuxdeployqt
    script:
    - misc/travis/linux-clang.sh
  - os: osx
    osx_image: xcode11.5
    before_script:
    - brew update
    - brew install qt5
    - brew link --force qt
    - brew install ninja
    - brew install ccache
    - export PATH="/usr/local/opt/ccache/libexec:$PATH"
    - npm install -g appdmg
    script:
    - misc/travis/macos.sh
  - os: windows
    before_script:
    - curl -vLO http://download.qt-project.org/official_releases/qt/5.14/5.14.2/qt-opensource-windows-x86-5.14.2.exe
    - echo "1.1.1.1 iapi.qt.io" > /c/Windows/System32/drivers/etc/hosts
    - ipconfig //flushdns
    - "./qt-opensource-windows-x86-5.14.2.exe --verbose --script misc/qt-installer-windows.qs"
    - choco install visualstudio2019community
    - choco install visualstudio2019-workload-nativedesktop
    - choco install ninja
    - choco install nsis
    script:
    - cmd //c "call misc\\travis\\windows.bat"
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: K2pfDCVMGUaec09F+9wFRCb3M+NJe78jELE9IN/6p3f0xEnEk8kD5wYdma8RwyfQaaUKsveGdibOGPqHqPTKI9S5AtzO4WuCGYNESeem9Z4Cu+fYbfLpPlqX4hBKwJYc/xOx9XNuugeGZq5JhysDkMktcdhhXC47Ly4oMvzMhtRlXjKHgpe4bSZ17Pb2vGDIjqA+rXTGZED4ok4VHVmk5NiNGdbGf7MaXTwYqY3KFRlBfNHeLTefoll2PB+s6w/5CcLtRjkMXQM88itvtubF1OXRD3gn7IESmzQC+Q1bTMrFtGGr2rXkx+qr459cBarXUDT9jihwf2DasnryZNxByKaWvbKc/JBTcFYJQkvG24mwN2sWE4j//uQofW2GOQR7LW6XfNo+0OL62YQ6lY0HVAjph3NBjGUf8rzdbVEX8L/it1qNY+ZygaQNUKtypt8F2Pq0b0qEn8aAP5d3f26JvTyvJhVeXneb+HcwSYE1/upq2YWV6qObM9U5b8C/YbaAzTGxO8wx6g92k4937/fyvoI4G2yKWFYdTjluQq2MTxbLki3Sb4r1A+fRHdta5paK+h6TZzjdIEL+whPd59S4/f1DCu9wukuGYcY3vh+B7SOojIHVALrYDqx9Jv9YrB0fwYrzrSzljCx56G+DFzWB7JZFm2ymZuBEBsxVBvS8vQw=
  file_glob: true
  file:
  - build/gcc/Graphia-*.tar.gz
  - build/Graphia-*.dmg
  - build/Graphia-*-installer.exe
  on:
    tags: true
after_deploy:
  - scripts/upload-symbols.sh
